# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newvectordialogbase.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_NewVectorLayerDialogBase(object):
    def setupUi(self, NewVectorLayerDialogBase):
        NewVectorLayerDialogBase.setObjectName(_fromUtf8("NewVectorLayerDialogBase"))
        NewVectorLayerDialogBase.resize(444, 647)
        NewVectorLayerDialogBase.setModal(True)
        self.gridLayout_2 = QtGui.QGridLayout(NewVectorLayerDialogBase)
        self.gridLayout_2.setMargin(11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.mFilePathLineEdit = QtGui.QLineEdit(NewVectorLayerDialogBase)
        self.mFilePathLineEdit.setObjectName(_fromUtf8("mFilePathLineEdit"))
        self.horizontalLayout.addWidget(self.mFilePathLineEdit)
        self.mBrowseFilePathButton = QtGui.QToolButton(NewVectorLayerDialogBase)
        self.mBrowseFilePathButton.setObjectName(_fromUtf8("mBrowseFilePathButton"))
        self.horizontalLayout.addWidget(self.mBrowseFilePathButton)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setMargin(11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.mFileFormatLabel_2 = QtGui.QLabel(NewVectorLayerDialogBase)
        self.mFileFormatLabel_2.setEnabled(True)
        self.mFileFormatLabel_2.setObjectName(_fromUtf8("mFileFormatLabel_2"))
        self.gridLayout.addWidget(self.mFileFormatLabel_2, 0, 0, 1, 1)
        self.mFileEncoding = QtGui.QComboBox(NewVectorLayerDialogBase)
        self.mFileEncoding.setEnabled(True)
        self.mFileEncoding.setObjectName(_fromUtf8("mFileEncoding"))
        self.gridLayout.addWidget(self.mFileEncoding, 0, 1, 1, 1)
        self.mCrsLabel = QtGui.QLabel(NewVectorLayerDialogBase)
        self.mCrsLabel.setObjectName(_fromUtf8("mCrsLabel"))
        self.gridLayout.addWidget(self.mCrsLabel, 1, 0, 1, 1)
        self.mCrsButton = QtGui.QPushButton(NewVectorLayerDialogBase)
        self.mCrsButton.setObjectName(_fromUtf8("mCrsButton"))
        self.gridLayout.addWidget(self.mCrsButton, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(NewVectorLayerDialogBase)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridlayout = QtGui.QGridLayout(self.groupBox)
        self.gridlayout.setMargin(11)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.textLabel1 = QtGui.QLabel(self.groupBox)
        self.textLabel1.setObjectName(_fromUtf8("textLabel1"))
        self.gridlayout.addWidget(self.textLabel1, 0, 0, 1, 1)
        self.mNameEdit = QtGui.QLineEdit(self.groupBox)
        self.mNameEdit.setObjectName(_fromUtf8("mNameEdit"))
        self.gridlayout.addWidget(self.mNameEdit, 0, 1, 1, 4)
        self.textLabel2 = QtGui.QLabel(self.groupBox)
        self.textLabel2.setObjectName(_fromUtf8("textLabel2"))
        self.gridlayout.addWidget(self.textLabel2, 1, 0, 1, 1)
        self.mTypeBox = QtGui.QComboBox(self.groupBox)
        self.mTypeBox.setObjectName(_fromUtf8("mTypeBox"))
        self.gridlayout.addWidget(self.mTypeBox, 1, 1, 1, 4)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridlayout.addWidget(self.label, 2, 0, 1, 1)
        self.mWidth = QtGui.QLineEdit(self.groupBox)
        self.mWidth.setObjectName(_fromUtf8("mWidth"))
        self.gridlayout.addWidget(self.mWidth, 2, 1, 1, 2)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridlayout.addWidget(self.label_2, 2, 3, 1, 1)
        self.mPrecision = QtGui.QLineEdit(self.groupBox)
        self.mPrecision.setObjectName(_fromUtf8("mPrecision"))
        self.gridlayout.addWidget(self.mPrecision, 2, 4, 1, 1)
        self.mAddAttributeButton = QtGui.QToolButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mAddAttributeButton.sizePolicy().hasHeightForWidth())
        self.mAddAttributeButton.setSizePolicy(sizePolicy)
        self.mAddAttributeButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../images/themes/default/mActionNewAttribute.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mAddAttributeButton.setIcon(icon)
        self.mAddAttributeButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.mAddAttributeButton.setObjectName(_fromUtf8("mAddAttributeButton"))
        self.gridlayout.addWidget(self.mAddAttributeButton, 4, 4, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 2, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(NewVectorLayerDialogBase)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridlayout1 = QtGui.QGridLayout(self.groupBox_2)
        self.gridlayout1.setMargin(11)
        self.gridlayout1.setSpacing(6)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.mAttributeView = QtGui.QTreeWidget(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mAttributeView.sizePolicy().hasHeightForWidth())
        self.mAttributeView.setSizePolicy(sizePolicy)
        self.mAttributeView.setAlternatingRowColors(True)
        self.mAttributeView.setRootIsDecorated(False)
        self.mAttributeView.setColumnCount(4)
        self.mAttributeView.setObjectName(_fromUtf8("mAttributeView"))
        self.gridlayout1.addWidget(self.mAttributeView, 2, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(121, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem, 3, 0, 1, 1)
        self.mRemoveAttributeButton = QtGui.QToolButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mRemoveAttributeButton.sizePolicy().hasHeightForWidth())
        self.mRemoveAttributeButton.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../../images/themes/default/mActionDeleteAttribute.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mRemoveAttributeButton.setIcon(icon1)
        self.mRemoveAttributeButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.mRemoveAttributeButton.setObjectName(_fromUtf8("mRemoveAttributeButton"))
        self.gridlayout1.addWidget(self.mRemoveAttributeButton, 3, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 3, 0, 1, 1)
        self.mButtonBox = QtGui.QDialogButtonBox(NewVectorLayerDialogBase)
        self.mButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.mButtonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Help|QtGui.QDialogButtonBox.Ok)
        self.mButtonBox.setObjectName(_fromUtf8("mButtonBox"))
        self.gridLayout_2.addWidget(self.mButtonBox, 4, 0, 1, 1)
        self.textLabel1.setBuddy(self.mNameEdit)
        self.textLabel2.setBuddy(self.mTypeBox)
        self.label.setBuddy(self.mWidth)
        self.label_2.setBuddy(self.mPrecision)

        self.retranslateUi(NewVectorLayerDialogBase)
        QtCore.QObject.connect(self.mButtonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), NewVectorLayerDialogBase.accept)
        QtCore.QObject.connect(self.mButtonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), NewVectorLayerDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(NewVectorLayerDialogBase)
        NewVectorLayerDialogBase.setTabOrder(self.mFileEncoding, self.mNameEdit)
        NewVectorLayerDialogBase.setTabOrder(self.mNameEdit, self.mTypeBox)
        NewVectorLayerDialogBase.setTabOrder(self.mTypeBox, self.mWidth)
        NewVectorLayerDialogBase.setTabOrder(self.mWidth, self.mPrecision)
        NewVectorLayerDialogBase.setTabOrder(self.mPrecision, self.mAddAttributeButton)
        NewVectorLayerDialogBase.setTabOrder(self.mAddAttributeButton, self.mAttributeView)
        NewVectorLayerDialogBase.setTabOrder(self.mAttributeView, self.mRemoveAttributeButton)
        NewVectorLayerDialogBase.setTabOrder(self.mRemoveAttributeButton, self.mButtonBox)

    def retranslateUi(self, NewVectorLayerDialogBase):
        NewVectorLayerDialogBase.setWindowTitle(_translate("NewVectorLayerDialogBase", "New Shapefile Layer", None))
        self.mBrowseFilePathButton.setText(_translate("NewVectorLayerDialogBase", "...", None))
        self.mFileFormatLabel_2.setText(_translate("NewVectorLayerDialogBase", "File encoding", None))
        self.mCrsLabel.setText(_translate("NewVectorLayerDialogBase", "CRS", None))
        self.mCrsButton.setText(_translate("NewVectorLayerDialogBase", "Select...", None))
        self.groupBox.setTitle(_translate("NewVectorLayerDialogBase", "New field", None))
        self.textLabel1.setText(_translate("NewVectorLayerDialogBase", "Name", None))
        self.textLabel2.setText(_translate("NewVectorLayerDialogBase", "Type", None))
        self.label.setText(_translate("NewVectorLayerDialogBase", "Length", None))
        self.label_2.setText(_translate("NewVectorLayerDialogBase", "Precision", None))
        self.mAddAttributeButton.setToolTip(_translate("NewVectorLayerDialogBase", "Add field to list", None))
        self.mAddAttributeButton.setText(_translate("NewVectorLayerDialogBase", "Add to fields list", None))
        self.groupBox_2.setTitle(_translate("NewVectorLayerDialogBase", "Fields list", None))
        self.mAttributeView.headerItem().setText(0, _translate("NewVectorLayerDialogBase", "Name", None))
        self.mAttributeView.headerItem().setText(1, _translate("NewVectorLayerDialogBase", "Type", None))
        self.mAttributeView.headerItem().setText(2, _translate("NewVectorLayerDialogBase", "Length", None))
        self.mAttributeView.headerItem().setText(3, _translate("NewVectorLayerDialogBase", "Precision", None))
        self.mRemoveAttributeButton.setToolTip(_translate("NewVectorLayerDialogBase", "Delete selected field", None))
        self.mRemoveAttributeButton.setText(_translate("NewVectorLayerDialogBase", "Remove field", None))

